// Code generated by protoc-gen-go. DO NOT EDIT.
// source: guest/guest.proto

package wedapi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Guest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Table                int32    `protobuf:"varint,4,opt,name=table,proto3" json:"table,omitempty"`
	Relation             string   `protobuf:"bytes,5,opt,name=relation,proto3" json:"relation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Guest) Reset()         { *m = Guest{} }
func (m *Guest) String() string { return proto.CompactTextString(m) }
func (*Guest) ProtoMessage()    {}
func (*Guest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f93fe0e9918f57df, []int{0}
}

func (m *Guest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Guest.Unmarshal(m, b)
}
func (m *Guest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Guest.Marshal(b, m, deterministic)
}
func (m *Guest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Guest.Merge(m, src)
}
func (m *Guest) XXX_Size() int {
	return xxx_messageInfo_Guest.Size(m)
}
func (m *Guest) XXX_DiscardUnknown() {
	xxx_messageInfo_Guest.DiscardUnknown(m)
}

var xxx_messageInfo_Guest proto.InternalMessageInfo

func (m *Guest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Guest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Guest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Guest) GetTable() int32 {
	if m != nil {
		return m.Table
	}
	return 0
}

func (m *Guest) GetRelation() string {
	if m != nil {
		return m.Relation
	}
	return ""
}

// The request message containing the user's name.
type GetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f93fe0e9918f57df, []int{1}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Guest)(nil), "guest.Guest")
	proto.RegisterType((*GetRequest)(nil), "guest.GetRequest")
}

func init() {
	proto.RegisterFile("guest/guest.proto", fileDescriptor_f93fe0e9918f57df)
}

var fileDescriptor_f93fe0e9918f57df = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4f, 0x83, 0x30,
	0x14, 0xc6, 0x2d, 0xd8, 0x45, 0x5e, 0xa6, 0xc9, 0x1a, 0x13, 0xc9, 0xdc, 0x81, 0x70, 0x30, 0x9c,
	0x20, 0xd1, 0xff, 0x60, 0x1e, 0xb8, 0x99, 0x05, 0x0f, 0x26, 0x9e, 0x2c, 0xf4, 0xc9, 0x9a, 0x00,
	0xc5, 0x52, 0x24, 0x3b, 0xfb, 0x8f, 0x1b, 0x8a, 0x9b, 0x19, 0x97, 0xa6, 0xbf, 0xf7, 0x7d, 0x2f,
	0xfd, 0xfa, 0xc1, 0xaa, 0xec, 0xb1, 0x33, 0x89, 0x3d, 0xe3, 0x56, 0x2b, 0xa3, 0x18, 0xb5, 0x10,
	0xfe, 0x10, 0xa0, 0xe9, 0x78, 0x63, 0x37, 0xe0, 0x48, 0xe1, 0x93, 0x80, 0x44, 0x6e, 0xe6, 0x48,
	0xc1, 0x36, 0xe0, 0x7d, 0x4a, 0xdd, 0x99, 0x17, 0x5e, 0xa3, 0xef, 0x04, 0x24, 0xf2, 0xb2, 0xff,
	0x01, 0x5b, 0xc3, 0x55, 0xc5, 0xff, 0x44, 0xd7, 0x8a, 0x27, 0x66, 0xb7, 0x40, 0x0d, 0xcf, 0x2b,
	0xf4, 0x2f, 0x03, 0x12, 0xd1, 0x6c, 0x82, 0x71, 0x43, 0x63, 0xc5, 0x8d, 0x54, 0x8d, 0x4f, 0xa7,
	0x8d, 0x23, 0x87, 0x1b, 0x80, 0x14, 0x4d, 0x86, 0x5f, 0xb3, 0x24, 0xde, 0x98, 0xe4, 0xf1, 0x03,
	0x96, 0x36, 0xe2, 0x2b, 0xea, 0x6f, 0x59, 0x20, 0x7b, 0x80, 0xc5, 0xb3, 0x46, 0x6e, 0x90, 0x2d,
	0xe3, 0xe9, 0x4b, 0x56, 0x5e, 0x9f, 0x51, 0x78, 0xc1, 0x22, 0x70, 0x53, 0x34, 0x6c, 0x75, 0x1c,
	0x9f, 0x5e, 0x98, 0x3b, 0xb7, 0x29, 0xdc, 0x15, 0xaa, 0x8e, 0x07, 0x14, 0x42, 0x36, 0x65, 0x8b,
	0x4d, 0x21, 0xab, 0xc9, 0xb2, 0xbd, 0x7e, 0x43, 0x61, 0x6d, 0xbb, 0xb1, 0xb6, 0x1d, 0x79, 0xbf,
	0x2f, 0xa5, 0xd9, 0xef, 0xfb, 0x3c, 0x2e, 0x54, 0x9d, 0x74, 0x07, 0xd1, 0xe0, 0x61, 0xe8, 0x93,
	0x01, 0x05, 0x6f, 0x65, 0xbe, 0xb0, 0xe5, 0x3e, 0xfd, 0x06, 0x00, 0x00, 0xff, 0xff, 0x54, 0xfb,
	0xdd, 0xfd, 0x71, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GuestServiceClient is the client API for GuestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GuestServiceClient interface {
	Create(ctx context.Context, in *Guest, opts ...grpc.CallOption) (*Guest, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Guest, error)
}

type guestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGuestServiceClient(cc grpc.ClientConnInterface) GuestServiceClient {
	return &guestServiceClient{cc}
}

func (c *guestServiceClient) Create(ctx context.Context, in *Guest, opts ...grpc.CallOption) (*Guest, error) {
	out := new(Guest)
	err := c.cc.Invoke(ctx, "/guest.GuestService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guestServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Guest, error) {
	out := new(Guest)
	err := c.cc.Invoke(ctx, "/guest.GuestService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuestServiceServer is the server API for GuestService service.
type GuestServiceServer interface {
	Create(context.Context, *Guest) (*Guest, error)
	Get(context.Context, *GetRequest) (*Guest, error)
}

// UnimplementedGuestServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGuestServiceServer struct {
}

func (*UnimplementedGuestServiceServer) Create(ctx context.Context, req *Guest) (*Guest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedGuestServiceServer) Get(ctx context.Context, req *GetRequest) (*Guest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterGuestServiceServer(s *grpc.Server, srv GuestServiceServer) {
	s.RegisterService(&_GuestService_serviceDesc, srv)
}

func _GuestService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Guest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guest.GuestService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestServiceServer).Create(ctx, req.(*Guest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuestService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guest.GuestService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GuestService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "guest.GuestService",
	HandlerType: (*GuestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _GuestService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _GuestService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guest/guest.proto",
}
